import React, { useState } from "react";
import "./Login.css";
import "./Card/Card";
import Card from "./Card/Card";
import Verification from "./Verification/Verification";
import Forgot from "../Forgot/Forgot";
import { Outlet, useLocation, useParams } from "react-router-dom";
import Reset from "./Reset/Reset";

function Login({
  setIsFlipped,
  isFlipped,
  setIsVerification,
  isVerification,
  setNavText,
}) {
  const [signupName, setSignupName] = useState("");
  const [signupEmail, setSignupEmail] = useState("");
  const [signupPassword, setSignupPassword] = useState("");

  const location = useLocation();
  const isForgot = location.pathname === "/forgot-password";

  return (
    <div className="Login-page">
      <div className={`BgAnimation ${isFlipped ? "Signheight" : "Logheight"}`}>
        <div className="BackgroundAnim"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
        <div className="colorBox"></div>
      </div>
      {isVerification ? (
        <Verification
          email={signupEmail}
          name={signupName}
          password={signupPassword}
          setNavText={setNavText}
          setIsFlipped={setIsFlipped}
          setIsVerification={setIsVerification}
        />
      ) : isForgot ? (
        <Outlet />
      ) : (
        <>
          <Card
            isFlipped={isFlipped}
            setIsVerification={setIsVerification}
            setSignupEmail={setSignupEmail}
            setSignupName={setSignupName}
            setSignupPassword={setSignupPassword}
            signupEmail={signupEmail}
            signupName={signupName}
            signupPassword={signupPassword}
          />
        </>
      )}
    </div>
  );
}

export default Login;
